trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  displayName: "Install Terraform"
  inputs:
    terraformVersion: '1.3.9'  # Especifica la versión de Terraform que deseas usar
    terraformDownloadLocation: 'https://releases.hashicorp.com/terraform'

- script: terraform init
  workingDirectory: 'terraform'  # Asegúrate de que apunte a la carpeta donde están tus archivos .tf
  displayName: 'Terraform Init'

- script: terraform plan -out=tfplan
  workingDirectory: 'terraform'
  displayName: 'Terraform Plan'

- script: terraform apply -input=false tfplan
  workingDirectory: 'terraform'
  displayName: 'Terraform Apply'

